package com.procex.procexapp.presentation.screens.client.formulario.create

data class ClientFormularioCreateState(
    val estado: String = "",
    val name_med: String = "",
    val name: String = "",
    val tipo_documento: String = "",
    val num_documento: String = "",
    val sexo: String = "",
    val RH: String = "",
    val fecha: String = "",
    val telefono: String = "",
    val tipo_visita: String = "",
    val cl_visita: String = "",
    val causa: String = "",
    val direccion: String = "",
    val barrio: String = "",
    val propiedad: String = "",
    val tensiona: String = "",
    val tipo_ta: String = "",
    val toma_ta: String = "",
    val oximetria: String = "",
    val toma_oxi: String = "",
    val resultado_oxi: String = "",
    val findrisk: String = "",
    val estatura: String = "",
    val peso: String = "",
    val nota_uno: String = "",
    val image: String = "",
)
